name: lmwrapper
channels:
  - conda-forge
  - pytorch
  # Nightlies:
  # - pytorch-nightly
  - huggingface
  # CUDA:
  # - nvidia
dependencies:
  # On MacOS for accelerated numpy
  # - libblas=*=*accelerate
  - python~=3.11.6
  - openai~=0.28.1
  - diskcache~=5.6.3
  - joblib~=1.3.2
  - tiktoken~=0.5.1
  - transformers~=4.34.1
  - pytest~=7.4.2
  - pytest-cov~=4.1.0
  # On MacOS
  - pytorch::pytorch~=2.1.0
  # On Linux
  # - pytorch~=2.1.0
  # CUDA:
  # - pytorch-cuda=12.1
  # CPU:
  # - cpuonly
  - humanize~=4.8.0
  - black~=23.10.0
  - ruff~=0.1.1
  - optimum~=1.13.2
  - onnxruntime
  - accelerate~=0.23.0
  pip:
    - bitsandbytes~=0.41.1
    - xformers
    - flash_attn

# To setup latest (from main) HF libraries, run:
# python -m pip install --upgrade --upgrade-strategy=eager --no-deps "peft @ git+https://github.com/huggingface/peft" "datasets @ git+https://github.com/huggingface/datasets" "evaluate @ git+https://github.com/huggingface/evaluate" "accelerate @ git+https://github.com/huggingface/accelerate" "optimum @ git+https://github.com/huggingface/optimum" "trl @ git+https://github.com/huggingface/trl" "transformers @ git+https://github.com/huggingface/transformers" "huggingface_hub @ git+https://github.com/huggingface/huggingface_hub" "exporters @ git+https://github.com/huggingface/exporters" "-e git+https://github.com/huggingface/tokenizers#egg=tokenizers&subdirectory=bindings/python" "setfit @ git+https://github.com/huggingface/setfit.git"