name: lmwrapper
channels:
  - conda-forge
  - pytorch
  # Nightlies:
  # - pytorch-nightly
  - huggingface
  - nvidia
dependencies:
  - python==3.11
  - openai
  - termcolor
  - diskcache
  - joblib
  - tiktoken
  - transformers
  - pytest
  # MacOS
  - pytorch::pytorch
  # Linux
  # - pytorch
  # CUDA:
  # - pytorch-cuda=12.1
  # CPU:
  # - cpuonly
  - humanize
  - black
  - ruff
  - onnx
  - datasets
  - evaluate
  - peft
  - optimum
  - onnxruntime
  pip:
    - bitsandbytes